### ISSUE TITLE
MainActivity (menu)

### ISSUE THREAD

**Issue by fearthedear** [fearthedear/Med44#1]
## **Why:**

Is the main menu of Med44.
## **Information:**

Large tiles will show the different options. Ideally the tiles show a preview of the activity it links to.
## **Todo:**
- [x] Make layout
- [x] Set up links
- [ ] Add background pictures of tiles
- [ ] show preview of activities
