### ISSUE TITLE
database

### ISSUE THREAD

**Issue by fearthedear** [fearthedear/Med44#2]
## **Why:**

We need a database to store the patient information.
## **Information:**

I'll add a database scheme here later.
## **Todo:**
- [x] make db scheme
- [x] set up sqlite android database
- [x] create tables
- [ ] test by filling with data
