### ISSUE TITLE
Prescriptions

### ISSUE THREAD

**Issue by fearthedear** [fearthedear/Med44#3]
## **Why:**
Integral part of Med44.

## **Information:**
Users can add their prescriptions, see the ones and when they have to take, and get info on the drugs (like side effects).

## **Todo:**
- [x] setup
- [x] shows what to do when no prescriptions
- [x] add adding functionaity
- [x] add functionality of showing prescriptions
- [ ] add delete functionality
