### ISSUE TITLE
Medical History

### ISSUE THREAD

**Issue by fearthedear** [fearthedear/Med44#4]
## **Why:**
main feature.

## **Information:**
Has two parts:
conditions and doc visits.

Large tiles will show the different options. Ideally the tiles show a preview of the activity it links to.
## **Todo:**
- [ ] setup
- [ ] implement two fragments: conditions and visits
- [ ] setup database add and display for conditions
- [ ] setup database add and display for visits
